In [1]:
import pandas as pd
roll_number = 1024170046
l = len(str(roll_number))
two_digits = str(roll_number)[l-2 : l : 1]

In [2]:
two_digits

'46'

In [3]:
fixed_entries = [
{"question": "what is the annual fee", "answer": "The annual fee is Rs 500.",
"keywords": "fee cost price charge", "category": "billing"},
{"question": "how to reset password", "answer": "Go to Settings > Reset Password.",
"keywords": "password reset login", "category": "account"},
{"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.",
"keywords": "hours timing open time", "category": "general"},
{"question": "how can i pay the fee", "answer":"You can pay via UPI, card, or net banking.",
"keywords": "pay payment upi fee", "category": "billing"},
]

In [4]:
fixed_entries

[{'question': 'what is the annual fee',
  'answer': 'The annual fee is Rs 500.',
  'keywords': 'fee cost price charge',
  'category': 'billing'},
 {'question': 'how to reset password',
  'answer': 'Go to Settings > Reset Password.',
  'keywords': 'password reset login',
  'category': 'account'},
 {'question': 'what are your working hours',
  'answer': 'We are open 9 AM to 5 PM.',
  'keywords': 'hours timing open time',
  'category': 'general'},
 {'question': 'how can i pay the fee',
  'answer': 'You can pay via UPI, card, or net banking.',
  'keywords': 'pay payment upi fee',
  'category': 'billing'}]

In [5]:
fixed_entries_df = pd.DataFrame(fixed_entries)

In [6]:
fixed_entries_df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

In [7]:
two_digits

'46'

In [8]:
category = ["billing","account","general"]
presonalized_entries = []
for i in two_digits:
  cat = int(i) % 3
  cat_1 = category[cat]
  if cat_1 == 'billing':
    faq = {
        "question" : "How  can i know about my current bill? ",
        "answer" : "By going to bank directly.",
        "keywords" : "Check current bill",
        "category" : cat_1
    }
  elif cat_1 == 'account':
    faq = {
        "question" : "How do I update my registered mobile number. ",
        "answer" : "Go to bank for this please.",
        "keywords" : "Mobile number change.",
        "category" : cat_1
    }
  else:
    faq = {
        "question" : "How are you doing",
        "answer" : "It is good",
        "keywords" : "how you doing",
        "category" : cat_1
    }
  presonalized_entries.append(faq)

In [9]:
presonalized_entries

[{'question': 'How do I update my registered mobile number. ',
  'answer': 'Go to bank for this please.',
  'keywords': 'Mobile number change.',
  'category': 'account'},
 {'question': 'How  can i know about my current bill? ',
  'answer': 'By going to bank directly.',
  'keywords': 'Check current bill',
  'category': 'billing'}]

In [10]:
for i in presonalized_entries:
  fixed_entries.append(i)

In [11]:
fixed_entries

[{'question': 'what is the annual fee',
  'answer': 'The annual fee is Rs 500.',
  'keywords': 'fee cost price charge',
  'category': 'billing'},
 {'question': 'how to reset password',
  'answer': 'Go to Settings > Reset Password.',
  'keywords': 'password reset login',
  'category': 'account'},
 {'question': 'what are your working hours',
  'answer': 'We are open 9 AM to 5 PM.',
  'keywords': 'hours timing open time',
  'category': 'general'},
 {'question': 'how can i pay the fee',
  'answer': 'You can pay via UPI, card, or net banking.',
  'keywords': 'pay payment upi fee',
  'category': 'billing'},
 {'question': 'How do I update my registered mobile number. ',
  'answer': 'Go to bank for this please.',
  'keywords': 'Mobile number change.',
  'category': 'account'},
 {'question': 'How  can i know about my current bill? ',
  'answer': 'By going to bank directly.',
  'keywords': 'Check current bill',
  'category': 'billing'}]

In [12]:
# question_ 2
def score_query(query,df):
  query_words = query.lower().split()
  result = []
  for index,row in df.iterrows():
    keywords = row['keywords'].lower().split()
    score = 0
    for word in query_words:
      if word in keywords:
        score = score + 1
    if score > 0:
      result.append({
          "question" : row['question'],
          "answer" : row['answer'],
          "score" : score
      })
  result.sort(key=lambda x : x['score'], reverse=True)
  return result

score_query("fee",fixed_entries_df)

[{'question': 'what is the annual fee',
  'answer': 'The annual fee is Rs 500.',
  'score': 1},
 {'question': 'how can i pay the fee',
  'answer': 'You can pay via UPI, card, or net banking.',
  'score': 1}]

In [13]:
fixed_entries_df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

In [14]:
# question 3
def same_category(category_name,df):
  result = []
  for index,row in df.iterrows():
    if row['category'] == category_name:
      result.append(row['question'])
  return result

In [15]:
same_category(presonalized_entries[0]["category"],fixed_entries_df)

['how to reset password']

In [17]:
# question 4
index = 0
new_keyword = input("Enter a new keyword: ")

fixed_entries_df.loc[index, "keywords"] = fixed_entries_df].loc[index, "keywords"] + " " + new_keyword

fixed_entries_df.to_csv(f"{roll_number}_faq_data.csv", index=False)

fixed_entries_df

Enter a new keyword: yigy

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge yigy,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing

In [18]:
# question 5
fixed_entries_df.groupby("category").size()

category
account    1
billing    2
general    1
dtype: int64

In [19]:
# question 6
def score_query_tie(query,df):
  query_words = query.lower().split()
  result = []
  for index,row in df.iterrows():
    keywords = row['keywords'].lower().split()
    score = 0
    for word in query_words:
      if word in keywords:
        score = score + 1
    if score > 0:
      result.append({
          "question" : row['question'],
          "answer" : row['answer'],
          "score" : score
      })

  result.sort(key=lambda x : x['score'], reverse=True)

  if len(result) == 0:
    return []

  highest_score = result[0]["score"]
  highest_matches = []

  for entry in result:
    if entry["score"] == highest_score:
      highest_matches.append(entry)

  if len(highest_matches) > 1:
    print("Multiple entries have the highest score:")
    for entry in highest_matches:
      print(entry)
  else:
    print("Highest scoring entry:")
    print(highest_matches[0])

  return result

# Query that produces a tie
score_query_tie("fee",fixed_entries_df)

# Query that does not produce a tie
score_query_tie("password",fixed_entries_df)

Multiple entries have the highest score:
{'question': 'what is the annual fee', 'answer': 'The annual fee is Rs 500.', 'score': 1}
{'question': 'how can i pay the fee', 'answer': 'You can pay via UPI, card, or net banking.', 'score': 1}
Highest scoring entry:
{'question': 'how to reset password', 'answer': 'Go to Settings > Reset Password.', 'score': 1}

[{'question': 'how to reset password',
  'answer': 'Go to Settings > Reset Password.',
  'score': 1}]